# Generated by Django 6.0.1 on 2026-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_auditevent_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organisation", "created_at"],
                name="projects_organis_cb765f_idx",
            ),
        ),
    ]
