# Generated by Django 6.0.1 on 2026-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_projects_organis_cb765f_idx"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "created_at"], name="tasks_project_a56d01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="tasks_status_031d4c_idx"),
        ),
    ]
