# Generated by Django 6.0.1 on 2026-02-04 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("target_type", models.CharField(blank=True, max_length=100)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "audit_events",
            },
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(fields=["owner"], name="organisatio_owner_i_ba2c26_idx"),
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(fields=["domain"], name="organisatio_domain_5d05bb_idx"),
        ),
        migrations.AddIndex(
            model_name="organisationmember",
            index=models.Index(
                fields=["organisation", "user"], name="organisatio_organis_e27342_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organisationmember",
            index=models.Index(fields=["user"], name="organisatio_user_id_83b3f8_idx"),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_events",
                to="organizations.organisation",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["organisation", "created_at"],
                name="audit_event_organis_7d2052_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(fields=["action"], name="audit_event_action_c7d4a3_idx"),
        ),
    ]
