# Generated by Django 6.0.1 on 2026-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_auditevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="domain",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
