# Generated by Codex on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_add_viewer_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actor_name", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("target_title", models.CharField(max_length=255)),
                ("org_id", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "activities",
                "indexes": [
                    models.Index(fields=["org_id", "created_at"], name="activity_org_created_idx"),
                ],
            },
        ),
    ]
